### ISSUE TITLE
conf : EC2 RDS 구축

### ISSUE THREAD

**Issue by Blooossom** [kdt-final-3/salarying-be#4]
## Description ( todo 설명 )

* 프로젝트 인프라 구성 
* 서버 인스턴스 : AWS EC2 - Ubuntu 20.04 LTS
* 데이터베이스 : AWS RDS - MariaDB

## Task ( todo )

- [x] EC2 서버구성
- [x] 외부접속을 위한 보안그룹 설정
- [x] Elastic IP를 통해 IP고정
- [x] RDS 생성
- [x] EC2와 동일한 보안그룹 지정

**Comment by crossbell8368** [comment]
## 데이터베이스 변경

* 프로젝트 발주처의 개발요건 확인 및 AWS RDS의 Free Tier 소진에 따른 DataBase 변경
* 요구 DataBase : Mysql 8.0.29
* 변경 DataBase : Synology NAS 서버에 Docker를 통해 Mysql DB 구축
* 외부접속을 위해 포트포워딩 & 보안설정 진행
* 프로젝트 CI/CD 담당 개발자분에게 정상접속 & 프로젝트 Branch 적용 확인
