### ISSUE TITLE
feat: 이메일 전송 api

### ISSUE THREAD

**Issue by jisoooit** [kdt-final-3/salarying-be#77]
## Description(설명)

지원자 알림 이메일 전송 기능
단체 지원자 이메일 전송 기능

## Tasks(New feature)

- [ ] email전송을 위한 dependency추가
- [ ] properties 파일에 설정 추가
- [ ] NoticeService 에 로직 추가
- [ ] emailReq 수정 (단체지원자 받을 수 있게 변경)
