### ISSUE TITLE
feat: 로그인 로직 반영하기 (토큰 받아서 활용)

### ISSUE THREAD

**Issue by jisoooit** [kdt-final-3/salarying-be#93]
## Description(설명)

인재보관함, 알림센터에 로그인 로직 반영하기

## Tasks(New feature)

- [x] controller에 로그인 유저 정보 받는 로직 추가
- [x] 받은 정보 service에 넘기기
- [x] config 파일 수정 ( permitAll 에서 제외하기 )
